### ISSUE TITLE
闪闪祭活动中奖池数和素材数对不上

### ISSUE THREAD

**Issue by 132conan** [ssttkkl/FGO-Planning-Tool#20]
比如计划20池时
辉石56个
魔石56个
秘石28个
蛇玉始终20个

**Comment by 132conan** [comment]
蛇眼的问题应该是资源包里面写错了。
还多了其他的东西，
但是饼干从13池起，每池=2倍。这个错误我没能理解

**Comment by ssttkkl** [comment]
蛇眼是我写错了
饼干*2这个问题有点诡异我还没找到原因

(我的设计是闪闪祭的金条在搬完商店后可以用来换QP，而12池的金条刚好搬完，所以12池之前和12池之后的素材单独计算。然而现在出bug了)

**Comment by ssttkkl** [comment]
OK我知道了，是资源包里某个标签打错了
