### ISSUE TITLE
泳裝牛若丸技能素材出錯

### ISSUE THREAD

**Issue by lih1017** [ssttkkl/FGO-Planning-Tool#9]
资源包已升到Battle in New York 2018(20180925)，LV6至7和7至8使用的素材应该是世界树之种，不是精灵根。
然后可以厚脸皮请求筛选功能吗？我把整个BOX都登录了，可是列表只能照NO排，没法照星数或阶级快速找到从者，有时眼残到可能要翻个一分多钟才能找到要记录的目标……
然后这真的很好用，谢谢大佬！ ！ ！

**Comment by ssttkkl** [comment]
(关于信息出错)感谢反馈，果然肉眼输信息容易出错……
(关于你说的筛选)你试下在选择从者的界面的右边缘向左滑或者按下右上方的按钮会发生什么……
________________________________

**Comment by lih1017** [comment]
可是大佬，已经登录过的角色是灰色的，不让二次编辑啊！
https://pan.baidu.com/s/1HYQ4gUDiyCkXjRbkbOsYIw
只有金时可以按，其他有练度的按不了

**Comment by ssttkkl** [comment]
主界面点一下……

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lih1017** [comment]
对不起是我没描述清楚
我知道可以在主页面再次编辑，可是比方说我用筛选功能找到4星狂活动赠送的茶茶，记录为灵基4技能666，等我练到999要记录的时候，很难在主页面找到位于中间排序的茶茶，只能慢慢翻，眼花就要翻好几次，还是说我太笨有我没发现的功能........
对不起浪费你刷箱子的时间

**Comment by ssttkkl** [comment]
你说的是这个啊……这个我确实没有做……

**Comment by ssttkkl** [comment]
正在锐意制作中了
